# Generated by Django 3.1.7 on 2021-05-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='name',
            new_name='url',
        ),
    ]
