# Generated by Django 3.1.7 on 2021-05-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
